- hosts: p1jenkins-pipeline
  become: yes
  tasks: 
    - name: Ensure dependencies are installed
      apt:
        name:
          - git
          - sshpass
          - wget
          - ansible
          - gnupg2
          - gnupg
          - curl
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Download jenkins repository apt URL
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        state: present

    - name: Ensure the repository is configured
      apt_repository: repo='deb https://pkg.jenkins.io/debian binary/' state=present

    - name: Update apt cache
      apt:
        update_cache: yes
        state: latest

    - name: Install java
      apt:
        name: 
          - openjdk-11-jdk
          - default-jre
        state: present

    - name: Install jenkins
      apt:
        name: jenkins
        state: latest

    - name: Start jenkins
      service:
        name: jenkins
        enabled: true
        state: started

    - name: Ensure docker is installed
      apt:
        name: docker.io
        state: latest
        update_cache: yes
    
    - name: Ensure docker-compose is installed
      apt:
        name: docker-compose
        state: latest
        update_cache: yes
    
    - name: Add jenkins user to docker group
      user:
        name: jenkins
        groups: docker
